### ISSUE TITLE
Pressing delete key in 'diagram' should delete a selected 'element'

### ISSUE THREAD

**Issue by sbmilburn** [mozilla/seasponge#65]
I was testing and creating a simple drawing. I created an object that I decided I didn't want to use that object. I pressed the delete key on my laptop and suddenly I went from the "draw" URL of http://mozilla.github.io/seasponge/#/draw back to the initial login screen of http://mozilla.github.io/seasponge/#/create and lost all objects in the diagram.  I testing this several times and could consistently repeat it. 

Browser - Chrome
OS - Mac OSX Yosemite 10.10.2

Expected behavior - object deleted not the entire diagram or at least a warning you're about to delete the entire diagram

**Comment by Glavin001** [comment]
This is both a bug and expected behaviour.

When you press delete in your web browser, it goes back in history to your previous page (as you noted). This is expected behaviour.

However, the bug in SeaSponge is actually the rendering / deserialization of the threat model in memory. I am testing now and can reproduce, however it is worth noting that even by creating a new model (see https://github.com/mozilla/seasponge/blob/master/app/scripts/controllers/create.coffee#L41-L51) it only changes the model title and other fields: it would actually leave your previous diagrams. This is a bug, likely related to #57.

SeaSponge actually has not lost the diagrams and their child elements and flows. If you open your JavaScript developer console you will notice that your threat model is being logged when you return into the `/#draw` route. Looking deeper at the child elements, in my tests, I still see the elements I had previously created.
There are also errors that occur after this log and involved in the render stages. This leads me to believe that there is a problem with the renderer, and it is not actually losing your model data.

I will look into the renderer and try and figure out why it is not deserializing and rendering properly.

Thanks!

**Comment by Glavin001** [comment]
I narrowed it down to https://github.com/mozilla/seasponge/blob/master/app/scripts/stencils/base.coffee#L93 

The `@$element.parent()` is returning a container (which it should not) instead of 0 items, so the element is not being appended to the container. Then because the element does not exist, the endpoints are failing to be created and that is the error I see later on.

I'm working on making it check to validate the parent it finds and if it is not valid, it will continue to continue to create the element and append it to the container and then this bug will go away.

**Comment by Glavin001** [comment]
Pushed patch. In about 3 minutes Travis CI will deploy this :+1:

**Comment by Glavin001** [comment]
With regards to the backspace/delete keypress making the web browser go backwards in history: http://stackoverflow.com/questions/1495219/how-can-i-prevent-the-backspace-key-from-navigating-back

I'm looking into that now.

- [ ] disable navigating web browser back on delete keypress
- [ ] delete selected element (if applicable) on delete keypress

**Comment by Glavin001** [comment]
All done. Should be deployed automatically in a few minutes. Let me know how it goes! Thanks.
